EFUB-LakkuLakku/LakkuLakku-Back

- .github/workflows/deploy.yml
- .gitignore
- Dockerfile
- config/nginx/Dockerfile
- config/nginx/nginx.conf
- deploy.sh
- docker-compose.yml
- src/main/resources/application.yml
- CI/CD 를 위한 도커 + 깃헙액션 설정
- secret 관리 후 application.yml 수정
> env: docker, github actions 설정

- .github/workflows/deploy.yml
- Dockerfile
- docker-compose.yml
- ec2에 아직 도커가 없으므로 5번째 스텝(remove useless images) 제외
- dockerfile 에서 working directory 설정 변경
resolves #2
> env: 배포 에러 해결 시도

- .github/workflows/deploy.yml
- 마지막 step 중 deploy.sh 위치 변경
resolves #2
> env: deploy.yml 수정

- Dockerfile
- docker-compose.yml
- build 시 test exclude
- jar 파일 이름 특정이 안되는 에러 -> 이름 특정 시도
제발.. 되길.....
resolves #2
> env: Dockerfile 수정

- src/main/java/com/efub/lakkulakku/domain/comment/entity/Comment.java
- src/main/java/com/efub/lakkulakku/domain/diary/entity/Diary.java
- src/main/java/com/efub/lakkulakku/domain/user/controller/LoginController.java
- src/main/java/com/efub/lakkulakku/domain/user/controller/WithdrawalController.java
- src/main/java/com/efub/lakkulakku/domain/user/dto/LoginReqDto.java
- src/main/java/com/efub/lakkulakku/domain/user/dto/LoginResDto.java
- src/main/java/com/efub/lakkulakku/domain/user/dto/WithdrawReqDto.java
- src/main/java/com/efub/lakkulakku/domain/user/repository/UserRepository.java
- src/main/java/com/efub/lakkulakku/domain/user/service/UserService.java
- src/main/java/com/efub/lakkulakku/global/constant/ResponseConstant.java
- src/main/resources/application.yml
- spring security 제외한 상태, 시큐리티 사용 이후 response data에 token값 반환 예정
- ResponseConstant: static 값들을 선언해 관리
- ExceptionHandler 설정 이후 에러 핸들링 추가 예정
resolves #5
> feat: /users/login - 로그인 api 1차 구현

- .github/workflows/deploy.yml
- config/scripts/delete.sh
- config/scripts/deploy.sh
- config/scripts/memory.sh
- memory.sh: 메모리 swap
- delete.sh: 사용하지 않는 도커 이미지 제거
> env: cpu 사용량 감소를 위한 쉘스크립트 작성

- build.gradle
- DiaryNotFoundException에서 .data를 인식하지 못해 빌드 실패되는 문제 해결
> fix: Exception 핸들링 중 필요한 패키지 설치

- src/main/java/com/efub/lakkulakku/domain/friend/entity/Friend.java
- src/main/java/com/efub/lakkulakku/domain/friend/repository/FriendRepository.java
- src/main/java/com/efub/lakkulakku/domain/users/repository/UsersRepository.java
- src/main/java/com/efub/lakkulakku/global/constant/ResponseConstant.java
- src/main/java/com/efub/lakkulakku/global/exception/ErrorCode.java
- src/main/java/com/efub/lakkulakku/global/exception/GlobalExceptionHandler.java
- 친구 추가, 검색, 조회, 삭제를 위한 기능 구현
- 친구 기능 예외 처리를 위해
GlobalExceptionHandler에 코드 추가
- 로그인 기능이 미완료 되어 로그인된 유저 연결 추가 구현 예정
resolves #21
> feat : /friends 기본 기능 1차 구현

- src/main/java/com/efub/lakkulakku/domain/friend/controller/FriendController.java
- src/main/java/com/efub/lakkulakku/domain/friend/dto/FriendReqDto.java
- src/main/java/com/efub/lakkulakku/domain/friend/dto/FriendResDto.java
- src/main/java/com/efub/lakkulakku/domain/friend/exception/DuplicateFriendException.java
- src/main/java/com/efub/lakkulakku/domain/friend/exception/UserNotFoundException.java
- src/main/java/com/efub/lakkulakku/domain/friend/repository/FriendRepository.java
- src/main/java/com/efub/lakkulakku/domain/friend/service/FriendService.java
- src/main/java/com/efub/lakkulakku/domain/users/exception/DuplicateEmailException.java
- src/main/java/com/efub/lakkulakku/domain/users/exception/DuplicateNicknameException.java
- src/main/java/com/efub/lakkulakku/global/exception/ErrorCode.java
- src/main/java/com/efub/lakkulakku/global/exception/ErrorResponse.java
- src/main/java/com/efub/lakkulakku/global/exception/GlobalExceptionHandler.java
> fix : 파일 추가 

- src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryHomeResDto.java
- src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
home 기능에서 일부 커밋이 main에 반영되지 않아 수정해서 다시 올립니다.
> feat: 사라진 커밋들 추가

- src/main/java/com/efub/lakkulakku/domain/users/dto/SignupReqDto.java
- src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
- src/test/java/com/efub/lakkulakku/domain/user/controller/LoginControllerTest.java
> feat : 비밀번호 암호화 적용

- src/main/java/com/efub/lakkulakku/domain/friend/controller/FriendController.java
- src/main/java/com/efub/lakkulakku/domain/friend/dto/FriendResDto.java
- src/main/java/com/efub/lakkulakku/domain/friend/service/FriendService.java
- src/main/java/com/efub/lakkulakku/domain/notification/dto/NotificationHomeResDto.java
- src/main/java/com/efub/lakkulakku/domain/notification/entity/Notification.java
> Feat: notification  알림 1차 구현 

- src/main/java/com/efub/lakkulakku/domain/diary/controller/DiaryEditController.java
- src/main/java/com/efub/lakkulakku/domain/stickerResource/dto/StickerResourceCategoryResDto.java
- src/main/java/com/efub/lakkulakku/domain/stickerResource/dto/StickerResourceMapper.java
- src/main/java/com/efub/lakkulakku/domain/stickerResource/dto/StickerResourceResDto.java
- src/main/java/com/efub/lakkulakku/domain/stickerResource/entity/StickerResource.java
- src/main/java/com/efub/lakkulakku/domain/stickerResource/repository/StickerResourceRepository.java
- src/main/java/com/efub/lakkulakku/domain/stickerResource/service/StickerResourceService.java
- src/main/java/com/efub/lakkulakku/domain/templateResource/dto/TemplateResourceDto.java
- src/main/java/com/efub/lakkulakku/domain/templateResource/dto/TemplateResourceMapper.java
- src/main/java/com/efub/lakkulakku/domain/templateResource/dto/TemplateResourceResDto.java
- src/main/java/com/efub/lakkulakku/domain/templateResource/repository/TemplateResourceRepository.java
- src/main/java/com/efub/lakkulakku/domain/templateResource/service/TemplateResourceService.java
- 속지 목록 조회
- 스티커 목록 조회(default, 최신순)
- 스티커 목록 조회(테마별)
3가지 완성했습니다!
> feat: /diaries/edit 다이어리 편집

- src/main/java/com/efub/lakkulakku/domain/likes/service/LikesService.java
> feat: /likes - 좋아요 message 수정

- src/main/java/com/efub/lakkulakku/domain/friend/service/FriendService.java
- src/main/java/com/efub/lakkulakku/domain/likes/controller/LikesController.java
- src/main/java/com/efub/lakkulakku/domain/likes/dto/LikeClickResDto.java
- src/main/java/com/efub/lakkulakku/domain/likes/dto/LikeMapper.java
- src/main/java/com/efub/lakkulakku/domain/likes/dto/LikeReqDto.java
- src/main/java/com/efub/lakkulakku/domain/likes/entity/Likes.java
- src/main/java/com/efub/lakkulakku/domain/likes/service/LikesService.java
- src/main/java/com/efub/lakkulakku/domain/notification/entity/Notification.java
-다이어리에서 좋아요 리스트 응답(likeResDto)과
좋아요 클릭시 보내는 응답(likeClickResDto)을 분리
-친구 알림과 좋아요 알림 수정
> fix: fix : 좋아요 커밋 후 충돌 오류 수정

- src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
> fix: 프론트 요청으로 CORS 문제 해결

- src/main/java/com/efub/lakkulakku/domain/comment/service/CommentService.java
- src/main/java/com/efub/lakkulakku/domain/profile/entity/Profile.java
-profile에서 Lazy로 설정되어있어 프로필 이미지를 불러올 수 없는
문제를 해결
> fix : 파일 불러오기 문제

- src/main/java/com/efub/lakkulakku/domain/users/controller/HomeController.java
홈 api 요청 방식 변경
홈 api 중 nickname을 parameter로 받았었는데, 보안 강화를 위해 이를 body로 넘겨줍니다.
> refactor: 홈 api request parameter -> request body

- src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
- 프론트에서 재발행 개발의 시간 단축을 위해 임시적으로 엑세스 토큰 유효 시간을 3분, 리프레시 토큰 유효시간을 5분으로 줄임
- 프론트에서 재발행 개발의 시간 단축을 위해 임시적으로 엑세스 토큰 유효 시간을 3분, 리프레시 토큰 유효시간을 5분으로 줄임
-프론트에서 재발급 개발 완료 이후 다시 토큰 시간을 늘릴 예정입니다.
> test : 토큰 시간 변경

- src/main/java/com/efub/lakkulakku/domain/users/controller/HomeController.java
프론트 요청 반영 : 홈 api request body -> param
프론트에서 axios 를 이용하면 get + request body 를 인식할 수 없다고 합니다. 따라서 이전 방식대로 get param 방식으로 nickname을 전달합니다.
> fix: 홈 api request body -> param

- src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
- 원래 토큰 시간인 엑세스토큰 => 2시간, 리프레시 토큰 => 1일으로 시간 변경
프론트 개발의 효율성을 위해 토큰 시간을 짧게 변경했다가 프론트 개발이 완성되어 원래 상태로 되돌려놓음
> fix : 토큰 시간 변경

- src/main/java/com/efub/lakkulakku/domain/profile/entity/Profile.java
- src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
- src/main/java/com/efub/lakkulakku/domain/users/entity/Users.java
- src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
- src/test/java/com/efub/lakkulakku/domain/user/controller/LoginControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/users/controller/LoginControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/users/controller/SignUpControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/users/controller/UsersControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/users/entity/UsersTest.java
- src/test/java/com/efub/lakkulakku/domain/users/repository/UsersRepositoryTest.java
- src/test/java/com/efub/lakkulakku/domain/users/service/LoginServiceTest.java
- src/test/java/com/efub/lakkulakku/domain/users/service/SignUpServiceTest.java
- src/test/java/com/efub/lakkulakku/global/config/AppConfigTest.java
- src/test/java/com/efub/lakkulakku/global/config/TestUsers.java
- src/test/java/com/efub/lakkulakku/global/config/WithUserDetailsSecurityContextFactory.java
- src/test/java/com/efub/lakkulakku/global/config/jwt/JwtProviderTest.java
- Users 도메인 테스트
- UsersRepository 실제 DB 테스트
- UsersService에서 회원 가입, 로그인 기능 테스트 코드 작성
- UsersController에서 회원 가입 테스트 코드 작성
- Users 도메인 테스트
- UsersRepository 실제 DB 테스트
- UsersService에서 회원 가입, 로그인 기능 테스트 코드 작성
- UsersController에서 회원 가입 테스트 코드 작성
solves : #96
> feat : 회원가입, 로그인 테스트 코드 작성

- src/main/java/com/efub/lakkulakku/domain/profile/controller/ProfileUpdateController.java
- src/test/java/com/efub/lakkulakku/domain/diary/controller/DiaryControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/users/controller/SignUpControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/users/controller/UsersControllerTest.java
- src/test/java/com/efub/lakkulakku/global/config/WithUserDetailsSecurityContextFactory.java
다이어리 생성 테스트 추가
1) 다이어리 생성 테스트 추가
2) ProfileUpdateController @PutMapping -> @PostMapping으로 변경
3) SignupController에서 회원가입 상태 코드 200 OK -> 201 CREATED로 변경
없음
> test: DiaryController 다이어리 생성 테스트 추가

- src/main/java/com/efub/lakkulakku/domain/comment/controller/CommentController.java
- src/main/java/com/efub/lakkulakku/domain/comment/dto/CommentReqDto.java
- src/main/java/com/efub/lakkulakku/domain/comment/service/CommentService.java
- src/main/java/com/efub/lakkulakku/domain/diary/controller/DiaryController.java
- src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryHomeMapper.java
- src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryMapper.java
- src/main/java/com/efub/lakkulakku/domain/diary/entity/Diary.java
- src/main/java/com/efub/lakkulakku/domain/diary/repository/DiaryRepository.java
- src/main/java/com/efub/lakkulakku/domain/diary/service/DiaryService.java
- src/main/java/com/efub/lakkulakku/domain/likes/controller/LikesController.java
- src/main/java/com/efub/lakkulakku/domain/likes/dto/LikeClickResDto.java
- src/main/java/com/efub/lakkulakku/domain/likes/dto/LikeMapper.java
- src/main/java/com/efub/lakkulakku/domain/likes/service/LikesService.java
- src/main/java/com/efub/lakkulakku/domain/profile/controller/ProfileUpdateController.java
- src/main/java/com/efub/lakkulakku/domain/users/entity/Users.java
- src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
- src/test/java/com/efub/lakkulakku/domain/comment/controller/CommentControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/diary/entity/DiaryTest.java
- src/test/java/com/efub/lakkulakku/domain/diary/service/DiaryServiceTest.java
- src/test/java/com/efub/lakkulakku/domain/likes/controller/LikesControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/likes/service/LikesServiceTest.java
- src/test/java/com/efub/lakkulakku/domain/profile/controller/ProfileUpdateControllerTest.java
- src/test/java/com/efub/lakkulakku/domain/profile/entity/ProfileTest.java
- src/test/java/com/efub/lakkulakku/domain/users/controller/UsersControllerTest.java
ProfileUpdateController test 코드 작성
- given(profileService.updateUserProfile(nickname, image, bio)).willReturn(expectedResponse); -> given(profileService.updateUserProfile(any(), any(), any())).willReturn(expectedResponse); 으로 변경 
-일단 mockMvcTestWithBuilder으로 만든 것과 의도한 값의 해시코드가 달라서 body 응답값이 null인 것을 임시 방편으로 해결하긴했지만 다른 해결방법이 있는지 고민해봐야할 것 같아요!
> feat : ProfileUpdateController test 코드 작성 + CommentController test코드 작성
